version: "3"

tasks:
  migrate:
    desc: "Migrations for sso service"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  run:
    desc: "Run sso service"
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yaml
